import assert from 'node:assert/strict';
import { parseCSV, stringifyCSV, csvFilename, sortCSVRows } from '../static/workflow-csv.js';
import { executeWorkflow, setVar, getPath } from '../static/workflow-runtime.js';

const input = '\uFEFFid,text,note\r\n001,"Hello, world","He said ""yes""."\r\n002,"two\r\nlines",café 日本語\r\n003,plain,\r\n';
const parsed = parseCSV(input);
assert.deepEqual(parsed.columns, ['id', 'text', 'note']);
assert.deepEqual(parsed.rows, [{ id:'001',text:'Hello, world',note:'He said "yes".' }, { id:'002',text:'two\r\nlines',note:'café 日本語' }, { id:'003',text:'plain',note:'' }]);
assert.deepEqual(parseCSV(stringifyCSV(parsed.rows, { columns: parsed.columns }).content).rows, parsed.rows);
for (const delimiter of [',',';','\t','|']) {
  const file=stringifyCSV(parsed.rows,{columns:parsed.columns,delimiter,bom:false});
  assert.equal(parseCSV(file.content).delimiter,delimiter);
  assert.deepEqual(parseCSV(file.content).rows,parsed.rows);
}
assert.deepEqual(parseCSV('\n\nname;value\nAda;007\n').rows,[{name:'Ada',value:'007'}]);
assert.deepEqual(parseCSV('name,value\na\n').rows,[{name:'a',value:''}]);
assert.deepEqual(parseCSV('name\n""\n').rows,[{name:''}]);
assert.deepEqual(parseCSV(stringifyCSV([{name:''}]).content).rows,[{name:''}]);
assert.deepEqual(parseCSV('a,b\n').rows,[]);
assert.deepEqual(parseCSV(stringifyCSV([],{columns:['a','b']}).content).columns,['a','b']);
for (const [text,pattern] of [['',/no header/],['a,a\n',/duplicated/],['a,\n',/blank/],['a,b\n1,2,3',/line 2.*3 fields/],['a\n"unterminated',/unterminated/],['a\n"b"oops',/after a closing quote/],['a\nb"c',/quote must start/]]) assert.throws(()=>parseCSV(text),pattern);
assert.throws(()=>stringifyCSV([null]),/row 1 must be an object/);
assert.throws(()=>stringifyCSV([['a']]),/row 1 must be an object/);
assert.throws(()=>stringifyCSV([]),/no columns/);
assert.throws(()=>stringifyCSV([],{columns:['a','a']}),/unique/);
assert.throws(()=>parseCSV('a,b',{delimiter:'x'}),/delimiter/);
assert.equal(csvFilename('../bad/file'), '.._bad_file.csv');
assert.equal(csvFilename('file.CSV'), 'file.CSV');
const odd = parseCSV('10,2,__proto__,constructor\n010,002,safe,yes\n');
assert.equal(Object.getPrototypeOf(odd.rows[0]),Object.prototype);
assert.equal(odd.rows[0].__proto__,'safe');
assert.deepEqual(parseCSV(stringifyCSV(odd.rows,{columns:odd.columns}).content).columns,odd.columns);
assert.equal(Object.prototype.safe,undefined);
assert.equal(getPath({item:{'customer.name':'Ada',"O'Reilly":'book'}},'item["customer.name"]'),'Ada');
assert.equal(getPath({item:{'customer.name':'Ada'}},"item['customer.name']"),'Ada');
assert.equal(getPath({item:{"O'Reilly":'book'}},'item["O\'Reilly"]'),'book');
assert.equal(getPath({rows:[{'column[0]':'yes'}]},'rows[0]["column[0]"]'),'yes');
assert.equal(getPath({item:{}},'item[broken]'),undefined);
const unsorted=[{id:'1',type:'support'},{id:'2',type:'billing'},{id:'3',type:'support'},{id:'4',type:''},{id:'5'}];
const sorted=sortCSVRows(unsorted,{sortBy:'type'});
assert.deepEqual(sorted.map(r=>r.id),['2','1','3','4','5']);
assert.deepEqual(unsorted.map(r=>r.id),['1','2','3','4','5'],'Sorting does not mutate the source list');
assert.deepEqual(sortCSVRows(unsorted,{sortBy:'type',sortDirection:'desc'}).map(r=>r.id),['1','3','2','4','5']);
assert.deepEqual(sortCSVRows([{n:10},{n:2}],{sortBy:'n'}),[{n:2},{n:10}]);
assert.throws(()=>sortCSVRows(unsorted,{sortBy:'missing'}),/not found/);
assert.throws(()=>sortCSVRows([{type:{}}],{sortBy:'type'}),/scalar/);
assert.throws(()=>sortCSVRows(unsorted,{sortBy:'type',sortDirection:'sideways'}),/direction/);
assert.deepEqual(sortCSVRows([],{sortBy:'type'}),[]);

const n=(id,type,config={})=>({id,type,label:id,config});
const e=(from,port,to)=>({id:`${from}-${to}`,from,fromPort:port,to});
const body={nodes:[n('input','input'),n('decision','decision',{key:'tag',state:'{{item.text}}',question:'Category?',options:[{key:'positive',description:'positive'},{key:'other',description:'other'}]}),n('out','output',{format:'json',value:'{"category": {{decisions.tag.choice}}, "confidence": {{decisions.tag.confidence}}}'})],edges:[e('input','next','decision'),e('decision','positive','out'),e('decision','other','out')]};
const flow={name:'Tag CSV',nodes:[n('csv','csv',{content:input,filename:'original.csv',resultAs:'rows'}),n('map','map',{source:'{{rows}}',resultAs:'tagged',mode:'workflow',keepOriginal:true,workflow:body}),n('export','csv-output',{source:'{{tagged}}',columns:'{{rowsCsv.columns}}',filename:'enriched.csv'})],edges:[e('csv','next','map'),e('map','done','export')]};
const calls=[];
const predict=async req=>{calls.push(req.state);return {answers:{tag:{choice:'positive',probabilities:{positive:.9,other:.1}}}};};
let seenFiles=false;
const result=await executeWorkflow(flow,{}, {predict,onTrace:update=>{if(update.files.length) seenFiles=true;}});
assert.deepEqual(calls,parsed.rows.map(r=>r.text));
assert.deepEqual(result.output,parsed.rows.map(r=>({...r,category:'positive',confidence:.9})));
assert.deepEqual(result.context.vars.rows,parsed.rows,'Tagging preserves the original rows');
assert.deepEqual(result.context.vars.rowsCsv,{columns:['id','text','note'],columnCount:3,delimiter:',',filename:'original.csv',rowCount:3});
assert.equal(seenFiles,true);
assert.equal(result.files.length,1);
assert.equal(result.files[0].filename,'enriched.csv');
assert.deepEqual(result.files[0].columns,['id','text','note','category','confidence']);
assert.deepEqual(parseCSV(result.files[0].content).rows,result.output.map(r=>({...r,confidence:'0.9'})));
assert.equal(result.trace.at(-1).file.rowCount,3);
assert.ok(!('content' in result.trace.at(-1).file),'Full CSV content stays outside bounded trace previews');
assert.ok(result.files[0].content.startsWith('\uFEFF'));
assert.deepEqual((await executeWorkflow(JSON.parse(JSON.stringify(flow)),{}, {predict})).output,result.output,'Embedded CSV is portable');

const empty=structuredClone(flow);empty.nodes[0].config.content='id,text,note\n';
const emptyResult=await executeWorkflow(empty,{}, {predict});
assert.equal(emptyResult.files[0].rowCount,0);
assert.deepEqual(emptyResult.trace[0].listCounts,{input:0,output:0});
assert.deepEqual(emptyResult.trace.at(-1).listCounts,{input:0,output:0});
assert.deepEqual(parseCSV(emptyResult.files[0].content).columns,['id','text','note']);
empty.nodes.at(-1).config.columns='["id","text","note","category","confidence"]';
assert.deepEqual(parseCSV((await executeWorkflow(empty,{})).files[0].content).columns,['id','text','note','category','confidence']);
empty.nodes.at(-1).config.columns='{{missing.columns}}';
await assert.rejects(executeWorkflow(empty,{}),/column order is missing/);
const wide={nodes:[n('csv','csv',{resultAs:'rows',content:Array.from({length:100},(_,i)=>`column${i}`).join(',')+'\n'}),n('out','csv-output',{source:'{{rows}}',columns:'{{rowsCsv.columns}}'})],edges:[e('csv','next','out')]};
const wideResult=await executeWorkflow(wide,{});
assert.equal(wideResult.trace[0].csv.columnCount,100);
assert.ok(wideResult.trace[0].csv.columns.length<100);
assert.equal(wideResult.trace[1].file.columnCount,100);
assert.ok(wideResult.trace[1].file.columns.length<100);
assert.equal(wideResult.files[0].columns.length,100);

const many=structuredClone(flow);many.nodes[0].config.content='id,text\n'+Array.from({length:400},(_,i)=>`${String(i).padStart(3,'0')},row ${i}`).join('\n');
many.nodes[1].config={source:'{{rows}}',resultAs:'tagged',format:'json',value:'{"category":"tagged"}',keepOriginal:true};
const manyResult=await executeWorkflow(many,{});
assert.equal(manyResult.files[0].rowCount,400);
assert.deepEqual(manyResult.trace.find(t=>t.type==='csv').listCounts,{input:400,output:400});
assert.deepEqual(manyResult.trace.find(t=>t.type==='map').listCounts,{input:400,output:400,processed:400});
assert.deepEqual(manyResult.trace.at(-1).listCounts,{input:400,output:400});
assert.equal(parseCSV(manyResult.files[0].content).rows.length,400,'Download includes rows beyond the preview limit');
assert.equal(parseCSV(manyResult.files[0].content).rows[399].id,'399');
assert.ok(manyResult.trace.at(-1).output.length<400);

const invalid=structuredClone(flow);invalid.nodes[0].config.content='id,id\n';
await assert.rejects(executeWorkflow(invalid,{}),error=>error.step.nodeId==='csv'&&/duplicated/.test(error.message)&&error.files.length===0);
const badMapping=structuredClone(many);badMapping.nodes[1].config.value='true';
await assert.rejects(executeWorkflow(badMapping,{}),error=>error.step.type==='map-value'&&error.step.iterations[0].index===0&&/requires.*objects/.test(error.message));
const template={nodes:[n('csv','csv',{mode:'template',source:'{{input.text}}',resultAs:'loaded'}),n('out','csv-output',{source:'{{loaded}}',columns:'{{loadedCsv.columns}}',filename:'{{input.filename}}',bom:false,delimiter:';'})],edges:[e('csv','next','out')]};
const templateResult=await executeWorkflow(template,{text:'id;name\n001;Ada',filename:'results'});
assert.equal(templateResult.files[0].filename,'results.csv');
assert.equal(templateResult.files[0].content,'id;name\r\n001;Ada\r\n');
const sortFlow={nodes:[n('out','csv-output',{source:'{{input}}',sortBy:'type',sortDirection:'asc'})],edges:[]};
const sortResult=await executeWorkflow(sortFlow,unsorted);
assert.deepEqual(sortResult.output.map(r=>r.id),['2','1','3','4','5']);
assert.deepEqual(parseCSV(sortResult.files[0].content).rows.map(r=>r.id),['2','1','3','4','5']);
assert.deepEqual(sortResult.trace[0].sort,{column:'type',direction:'asc'});

// Sharing immutable parent lists must retain nested write isolation.
const original={profile:{nested:{name:'parent'}},rows:[{id:'001'}]};
const ctx={vars:{...original}};
setVar(ctx,'profile.nested.name','child');
assert.equal(original.profile.nested.name,'parent');
assert.equal(ctx.vars.profile.nested.name,'child');
assert.equal(ctx.vars.rows,original.rows,'Untouched large datasets are shared, not copied per row');
setVar(ctx,'__proto__.polluted','no');
assert.equal(Object.prototype.polluted,undefined);
const isolated={nodes:[n('set','set',{assignments:[{path:'profile.nested.name',value:'child'},{path:'profile.copiedName',value:'{{profile.nested.name}}'}]}),n('out','output',{value:'{{profile}}'})],edges:[e('set','next','out')]};
const parent={nodes:[n('map','map',{source:'{{input}}',resultAs:'mapped',mode:'workflow',workflow:isolated}),n('out','output',{value:'{{profile}}'})],edges:[e('map','done','out')]};
const isolatedResult=await executeWorkflow(parent,{input:[1,2],vars:structuredClone(original),decisions:{},locals:{}});
assert.equal(isolatedResult.output.nested.name,'parent');
assert.ok(isolatedResult.context.vars.mapped.every(row=>row.nested.name==='child'));
assert.ok(isolatedResult.context.vars.mapped.every(row=>row.copiedName==='child'),'Sequential writes resolve the current item scope');
console.log('Workflow CSV import, tagging, export and scope-isolation checks passed.');
